-- AlterTable
ALTER TABLE "Booking" ADD COLUMN     "advanceAmount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "balanceDue" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "fare" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "finalPayable" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "gatewayCharge" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "gstAmount" INTEGER NOT NULL DEFAULT 0,
ALTER COLUMN "advancePaid" SET DEFAULT 0,
ALTER COLUMN "totalTariff" SET DEFAULT 0,
ALTER COLUMN "balancePayable" SET DEFAULT 0,
ALTER COLUMN "status" DROP DEFAULT,
ALTER COLUMN "paymentStatus" DROP DEFAULT;
