const { PrismaClient } = require("@prisma/client");
const prisma = new PrismaClient();

const FLEET_SEED_DATA = [
  {
    id: "sedan_4",
    name: "Sedan (4 Seater)",
    models: "Swift Dzire / Toyota Etios / Hyundai Aura",
    seats: 4,
    luggage: "2 Large Bags + 2 Handbags",
    category: "sedan",
    tag: "Most Popular for Small Families & Couples",
    badgeType: "gold",
    image: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=800&q=80",
    basePrice: 4551, // 8hr 80km
    baseHours: 8,
    baseKm: 80,
    nightPrice: 5051,
    perExtraHour: 200,
    outstationPerKm: 20,
    features: JSON.stringify([
      "Chilled Dual AC",
      "Sanitised & Clean Interior",
      "Kolkata Pandal Route Specialist Driver",
      "Complimentary Water Bottles",
      "Free Cancellation up to 24 hrs",
    ]),
    inclusions: JSON.stringify([
      "Base package 80 KMs & 8 Hours usage (₹4,551) or 50 KMs (₹3,551)",
      "Chilled Dual AC & Sanitised Interior",
      "Fuel Charges & Driver Day Allowance Included",
      "State & City Toll Taxes Included",
      "Free 24h Cancellation with 100% Refund",
    ]),
    exclusions: JSON.stringify([
      "Extra KMs beyond package (charged at ₹20/km)",
      "Extra Hours beyond package (charged at ₹200/hr)",
      "Night driving allowance (₹500 if operating past 10 PM)",
      "Specific pandal/mall parking entry tickets",
    ]),
  },
  {
    id: "suv_6",
    name: "SUV (6 Seater)",
    models: "Maruti Ertiga / Kia Carens / Renault Triber",
    seats: 6,
    luggage: "3 Large Bags + 3 Handbags",
    category: "suv",
    tag: "Best Value for Joint Families",
    badgeType: "crimson",
    image: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=800&q=80",
    basePrice: 5551, // 8hr 80km
    baseHours: 8,
    baseKm: 80,
    nightPrice: 6051,
    perExtraHour: 250,
    outstationPerKm: 25,
    features: JSON.stringify([
      "Spacious 3-Row AC",
      "High Ground Clearance for Crowded Alleys",
      "Dedicated Driver Mobile with Live GPS Tracking",
      "Senior Citizen Step-board Support",
      "24x7 Puja Control Room Support",
    ]),
    inclusions: JSON.stringify([
      "Base package 80 KMs & 8 Hours usage (₹5,551) or 50 KMs (₹4,551)",
      "Chilled 3-Row AC & Ample Legroom",
      "Fuel & Verified Chauffeur Allowance",
      "All Bengal Highway Tolls & Taxes Included",
      "Senior Citizen Close Drop Point Assistance",
    ]),
    exclusions: JSON.stringify([
      "Extra KMs beyond package (charged at ₹25/km)",
      "Extra Hours beyond package (charged at ₹250/hr)",
      "Night driving allowance (₹500 if operating past 10 PM)",
      "Private parking charges at venue/hotel",
    ]),
  },
  {
    id: "suv_7",
    name: "SUV+ (7 Seater)",
    models: "Toyota Innova Crysta / Hycross / Scorpio-N",
    seats: 7,
    luggage: "4 Large Bags + 4 Handbags",
    category: "suv",
    tag: "VIP Luxury & Ultimate Comfort",
    badgeType: "gold",
    image: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80",
    basePrice: 7551, // 8hr 80km
    baseHours: 8,
    baseKm: 80,
    nightPrice: 8051,
    perExtraHour: 300,
    outstationPerKm: 30,
    features: JSON.stringify([
      "Captain Recliner Seats",
      "Ultra-smooth Suspension for Senior Citizens",
      "Chauffeur in Uniform with 10+ Yr Experience",
      "Priority VIP Drop Point Knowledge",
      "In-car Phone Chargers & Wet Wipes",
    ]),
    inclusions: JSON.stringify([
      "Base package 80 KMs & 8 Hours usage (₹7,551) or 50 KMs (₹6,051)",
      "Luxury Captain Seats & Heavy-duty Dual AC",
      "Fuel & Senior Route-Master Chauffeur Allowance",
      "Fastag Highway Tolls & Taxes Included",
      "Complimentary Bengali Sweet Hamper Onboard",
    ]),
    exclusions: JSON.stringify([
      "Extra KMs beyond package (charged at ₹30/km)",
      "Extra Hours beyond package (charged at ₹300/hr)",
      "Night driving allowance (₹500 if operating past 10 PM)",
      "Designated pandal VIP parking access slips",
    ]),
  },
  {
    id: "traveller_13",
    name: "Tempo Traveller (13 Seater)",
    models: "Force Luxury Urbania / Tempo Traveller 3350",
    seats: 13,
    luggage: "8 Large Bags",
    category: "traveller",
    tag: "Ideal for Large Joint Families & Friends Groups",
    badgeType: "gold",
    image: "https://images.unsplash.com/photo-1570125909232-eb263c188f7e?auto=format&fit=crop&w=800&q=80",
    basePrice: 10051, // 8hr 80km
    baseHours: 8,
    baseKm: 80,
    nightPrice: 10551,
    perExtraHour: 400,
    outstationPerKm: 40,
    features: JSON.stringify([
      "Individual AC Vents on Every Seat",
      "Pushback 2x1 Luxury Seats",
      "Large Panoramic Windows for Illumination Views",
      "Ample Rear Luggage Space",
      "Assigned Senior Chauffeur & Cleaner",
    ]),
    inclusions: JSON.stringify([
      "Base package 80 KMs & 8 Hours usage (₹10,051) or 50 KMs (₹9,051)",
      "Individual AC Vents on Every Seat & Pushback Rows",
      "Fuel, Commercial Permit & Driver Allowances",
      "All West Bengal Highway Tolls Included",
      "Dedicated On-Call Operations Manager",
    ]),
    exclusions: JSON.stringify([
      "Extra KMs beyond package (charged at ₹40/km)",
      "Extra Hours beyond package (charged at ₹400/hr)",
      "Night driving allowance (₹500 if operating past 10 PM)",
      "Club/Pandal special heavy vehicle parking tickets",
    ]),
  },
  {
    id: "traveller_17",
    name: "Tempo Traveller (17 Seater)",
    models: "Force Executive Deluxe Traveller",
    seats: 17,
    luggage: "12 Large Bags",
    category: "traveller",
    tag: "Perfect for Corporate Teams & Para Clubs",
    badgeType: "crimson",
    image: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=800&q=80",
    basePrice: 11051, // 8hr 80km
    baseHours: 8,
    baseKm: 80,
    nightPrice: 11551,
    perExtraHour: 450,
    outstationPerKm: 45,
    features: JSON.stringify([
      "High Roof Walkthrough Cabin",
      "High Quality Bluetooth Audio for Agomoni & Puja Songs",
      "LED Ambient Mood Lighting",
      "Dedicated First Aid & Sanitisation Kit",
      "Police Route Permission Assistance",
    ]),
    inclusions: JSON.stringify([
      "Base package 80 KMs & 8 Hours usage (₹11,051) or 50 KMs (₹10,051)",
      "High Roof Cabin with Individual Blower ACs",
      "High-power Music System for Puja Agomoni Songs",
      "Driver + Assistant Chaperone Allowance Included",
      "All West Bengal Highway Tolls Included",
    ]),
    exclusions: JSON.stringify([
      "Extra KMs beyond package (charged at ₹45/km)",
      "Extra Hours beyond package (charged at ₹450/hr)",
      "Night driving allowance (₹500 if operating past 10 PM)",
      "Special club/hotel bus parking fees",
    ]),
  },
  {
    id: "traveller_24",
    name: "Tempo Traveller (24 Seater)",
    models: "Force Grand Luxury Coach / Urbania King 24s",
    seats: 24,
    luggage: "16 Large Bags",
    category: "traveller",
    tag: "Maximum Group Capacity & Royalty",
    badgeType: "gold",
    image: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=800&q=80",
    basePrice: 13051, // 8hr 80km
    baseHours: 8,
    baseKm: 80,
    nightPrice: 13551,
    perExtraHour: 500,
    outstationPerKm: 50,
    features: JSON.stringify([
      "Ultra Luxury Pushback Leather Seats",
      "Dual Heavy-duty Blower AC",
      "Microphone PA System for Tour Coordinators",
      "Extra Wide Aisles & Emergency Exit",
      "Guaranteed Reserve Vehicle on Standby",
    ]),
    inclusions: JSON.stringify([
      "Base package 80 KMs & 8 Hours usage (₹13,051) or 50 KMs (₹12,051)",
      "Ultra-luxury Pushback Leather Recliners & Dual AC",
      "Fuel, Commercial Permits & Driver Allowances",
      "All West Bengal Toll Taxes Included",
      "Guaranteed Backup Standby Vehicle",
    ]),
    exclusions: JSON.stringify([
      "Extra KMs beyond package (charged at ₹50/km)",
      "Extra Hours beyond package (charged at ₹500/hr)",
      "Night driving allowance (₹500 if operating past 10 PM)",
      "Special venue/club bus parking slip",
    ]),
  },
];

const PACKAGES_SEED_DATA = [
  {
    id: "pkg_5hr_50km",
    type: "rental",
    title: "5 Hours / 50 KMs Rental Package",
    subtitle: "Ideal for quick morning darshan, elderly-friendly short hops & Bonedi Bari heritage pandals",
    hoursKm: "5 Hours / 50 KMs",
    rentalType: "Morning Rentals",
    priceStarting: 3551,
    badge: "🌅 Morning Special",
    optimalTime: "08:00 AM – 01:00 PM",
    highlights: JSON.stringify([
      "Sovabazar Rajbari & Bagbazar Sarbojanin",
      "Kumartuli Park & Ahiritola Ghat",
      "College Square & Mohammed Ali Park",
      "Dedicated Chauffeur on Standby",
    ]),
    image: "https://images.unsplash.com/photo-1558431382-27e303142255?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "pkg_8hr_80km",
    type: "rental",
    title: "8 Hours / 80 KMs Rental Package",
    subtitle: "Most popular choice for prime evening illumination & mega pandals with dining adda halts",
    hoursKm: "8 Hours / 80 KMs",
    rentalType: "Evening Rentals",
    priceStarting: 4551,
    badge: "🔥 Most Popular",
    optimalTime: "04:00 PM – 12:00 Midnight",
    highlights: JSON.stringify([
      "Suruchi Sangha & Chetla Agrani",
      "Mudiali Club & Tridhara Sammilani",
      "Ekdalia Evergreen & Singhi Park",
      "Ballygunge Cultural & Badamtala",
    ]),
    image: "https://images.unsplash.com/photo-1567157577867-05ccb1388e66?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "pkg_10hr_100km",
    type: "rental",
    title: "10 Hours / 100 KMs Rental Package",
    subtitle: "Complete twin-circuit coverage of both North & South Kolkata iconic theme pandals in one trip",
    hoursKm: "10 Hours / 100 KMs",
    rentalType: "Full Day Circuit",
    priceStarting: 5051,
    badge: "⭐ Grand Explorer",
    optimalTime: "02:00 PM – 12:00 Midnight",
    highlights: JSON.stringify([
      "North Kolkata Bonedi Bari & Rajbari",
      "Salt Lake FD Block & Sreebhumi",
      "South Kolkata Theme Pandals",
      "Flexible Food & Adda Breaks",
    ]),
    image: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "pkg_12hr_120km",
    type: "rental",
    title: "12 Hours / 120 KMs Rental Package",
    subtitle: "Zero-traffic midnight to morning VIP Parikrama with peaceful darshan across top 20 pandals",
    hoursKm: "12 Hours / 120 KMs",
    rentalType: "Midnight VIP Tour",
    priceStarting: 6051,
    badge: "✨ Zero Traffic VIP",
    optimalTime: "08:00 PM – 08:00 AM",
    highlights: JSON.stringify([
      "Sreebhumi Sporting Club Light Show",
      "Santosh Mitra Square & Dum Dum Park",
      "Tala Prattoy & Kashi Bose Lane",
      "Ballygunge Cultural & Behala Club",
    ]),
    image: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80",
  },
  // 8 Outstation Routes
  {
    id: "kolkata-digha",
    type: "outstation",
    title: "Kolkata to Digha",
    subtitle: "Old Digha • New Digha • Marine Drive • Udaipur Beach",
    distance: "185 KM",
    estimatedTime: "4.5 Hours",
    priceStarting: 2899,
    badge: "🌊 Beach Gateway",
    highlights: JSON.stringify(["Kolkata to Digha Sea Beach", "Marine Drive & Udaipur Border", "Kolaghat Hilsa & Tea Stop", "Sanitised roundtrip AC cab"]),
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "kolkata-mayapur",
    type: "outstation",
    title: "Kolkata to Mayapur",
    subtitle: "ISKCON TOVP Temple • Ganga Aarti • Nabadwip Dham",
    distance: "130 KM",
    estimatedTime: "3.5 Hours",
    priceStarting: 2499,
    badge: "🛕 Spiritual Tour",
    highlights: JSON.stringify(["ISKCON Temple of Vedic Planetarium", "Ganga Arati at Mayapur Ghat", "Shantipur Handloom & Sweet hub", "Day trip / overnight booking"]),
    image: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "kolkata-mandarmani",
    type: "outstation",
    title: "Kolkata to Mandarmani",
    subtitle: "Beach Resort • Red Crab Beach • Tajpur Confluence",
    distance: "175 KM",
    estimatedTime: "4.5 Hours",
    priceStarting: 2999,
    badge: "🦀 Luxury Resorts",
    highlights: JSON.stringify(["Drive-in Sea Beach access", "Tajpur & Shankarpur coastal road", "Kolaghat food plaza halt", "Full festive weekend support"]),
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "kolkata-bolpur",
    type: "outstation",
    title: "Kolkata to Bolpur-Shantiniketan",
    subtitle: "Visva Bharati • Sonajhuri Haat • Kopai River",
    distance: "165 KM",
    estimatedTime: "4 Hours",
    priceStarting: 2799,
    badge: "🎨 Baul & Culture",
    highlights: JSON.stringify(["Visva-Bharati Ashram & Museum", "Saturday Sonajhuri Sanibarer Haat", "Shaktigarh Lyangcha tasting stop", "Chauffeur trained on Durgapur Exp"]),
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "kolkata-dhanbad",
    type: "outstation",
    title: "Kolkata to Dhanbad",
    subtitle: "Maithon Dam • Topchanchi Lake • Kalyaneshwari",
    distance: "270 KM",
    estimatedTime: "6 Hours",
    priceStarting: 4499,
    badge: "⛰️ Interstate Express",
    highlights: JSON.stringify(["Smooth NH19 Durgapur Expressway", "Maithon Dam & Boating Club", "Commercial toll tax handled", "Experienced highway chauffeur"]),
    image: "https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "kolkata-durgapur",
    type: "outstation",
    title: "Kolkata to Durgapur",
    subtitle: "Steel City • City Centre • Durgapur Barrage",
    distance: "170 KM",
    estimatedTime: "3.5 Hours",
    priceStarting: 2699,
    badge: "⚡ Fast Expressway",
    highlights: JSON.stringify(["Superfast NH19 Highway transit", "Durgapur Barrage & Damodar river", "Corporate & Family Festival Drops", "Door-to-door AC comfort"]),
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "kolkata-murshidabad",
    type: "outstation",
    title: "Kolkata to Murshidabad",
    subtitle: "Hazarduari Palace • Katra Mosque • Motijheel",
    distance: "240 KM",
    estimatedTime: "5.5 Hours",
    priceStarting: 3999,
    badge: "👑 Nawab Heritage",
    highlights: JSON.stringify(["Hazarduari 1000-Door Palace", "Nawabi cuisine & Murshidabad Silk", "Krishnanagar Sweet halt", "Custom 2-day return itineraries"]),
    image: "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "kolkata-ranchi",
    type: "outstation",
    title: "Kolkata to Ranchi",
    subtitle: "Hundru Falls • Jonha Falls • Patratu Valley",
    distance: "400 KM",
    estimatedTime: "8.5 Hours",
    priceStarting: 6499,
    badge: "🌲 Waterfall Escapes",
    highlights: JSON.stringify(["Scenic Patratu Valley Ghat drive", "Hundru & Dassam Waterfalls", "Jharkhand interstate permit handled", "Dual driver option on request"]),
    image: "https://images.unsplash.com/photo-1433086966358-54859d0ed716?auto=format&fit=crop&w=800&q=80",
  },
];

async function main() {
  console.log("🌱 Seeding BroomBoom Cabs Database with updated rate matrix...");

  // Seed Fleet
  for (const car of FLEET_SEED_DATA) {
    await prisma.fleet.upsert({
      where: { id: car.id },
      update: car,
      create: car,
    });
  }
  console.log(`✅ Seeded ${FLEET_SEED_DATA.length} Fleet Vehicles.`);

  // Seed Packages
  for (const pkg of PACKAGES_SEED_DATA) {
    await prisma.package.upsert({
      where: { id: pkg.id },
      update: pkg,
      create: pkg,
    });
  }
  console.log(`✅ Seeded ${PACKAGES_SEED_DATA.length} Rental & Outstation Packages.`);

  console.log("🌟 Seeding completed successfully!");
}

main()
  .catch((e) => {
    console.error("❌ Seeding failed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
